### ISSUE TITLE
Color Chooser Menu Disappears When Clicked

### ISSUE THREAD

**Issue by smolck** [pablopunk/vimcolors.org#4]
When I first open the website and click on one of the options, say `Color 1` as an example, things work just as expected; I can change the color with the various tools provided (hex, RGBA, etc.). However, if I afterwards try and choose another option, say `Background`, if I try to modify the hex field for example, after I click in the input box to change the hex value the whole menu disappears.

This happens in both Chromium and Firefox on Arch Linux (and even Safari on IOS); the first option works as expected, but all others after it close when anywhere in the color menu is clicked.

**Comment by pablopunk** [comment]
@smolck hmmm true, I'll investigate it, thanks!
