### ISSUE TITLE
Settings get reset when switching between dark/light

### ISSUE THREAD

**Issue by b3nj5m1n** [pablopunk/vimcolors.org#7]

**Comment by pablopunk** [comment]
Are you suggesting keeping the other colors and only change the background/foreground?

**Comment by b3nj5m1n** [comment]
Yes. I don't want to have to re do all of the settings, I just want to see what my current settings look like with dark/light bg. I'd suggest a separate reset button.

**Comment by pablopunk** [comment]
Ok I made simple. Now if you select "light", the colors won't change (not even the background, that's up to you to change it). It will only mean the downloaded file contains `set background=light` for vim.
